spring.application.name=certchain-backend
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/certchain
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Port
server.port=8080
# Blockchain
blockchain.alchemy.url=https://eth-sepolia.g.alchemy.com/v2/tgRoDvFnUMjh58s-gzX47
blockchain.private.key=f3a3863130cdb9aaa2000d40c602c600523606a8ea1943eef29c13f0183cdefa
blockchain.contract.address=0x27d0fbF48EF7D9Bd1b3c3404741DB7c6D50Bde94